# Site settings
title: Milner Commonplace Miscellany
description: A place to blog about things I'm learning/thinking about.

author:
  name: Lincoln Milner
  email: lincoln.milner@gmail.com

baseurl: ""
url: "https://lincolnmilner.github.io"
lang: "en-US"

google_analytics: "G-3RT0XR6QYC"

show_excerpts: true
date_format: "%m/%d/%Y"

social_links:
  - title: GitHub repository
    icon: github
    url: https://github.com/lincolnmilner
  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/lincolnmilner/


# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-seo-tag
