lsi: false
safe: true
source: lincolnmilner.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-modernist
title: Milner's Miscellany and Commonplace Book
description: Taking a stab at blogging in 2022 because why not?
