# Site settings
theme: jekyll-theme-dinky
title: Milner's Miscellany
author: Lincoln Milner
description: Taking a stab at blogging in 202x because why not?
baseurl: ""
url: "https://lincolnmilner.github.io"

# Google services
google_verification:
google_analytics: G-3RT0XR6QYC
google_tag_manager: GTM-PMGDPZV

github_username: lincolnmilner
stackoverflow_id: 16575
twitter_username: lincolnmilner
linkedin_username: lincolnmilner

sass:
  compressed: true
plugins:
  - jekyll-remote-theme
